= F# vs GO -  Functional Programming
Daniel Piotrowski <piodan@gmx.net>
1.1, December 21, 2020, Asciidoctor 1.5 article template
:toc:
:icons: font
:quick-uri: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

This article aims to compare the functional programming aspects of GOLang, which is currently maintained by Google, with Microsofts OCaml based functional programming language F#. It is written as a exam study paper, handed in and presented to fellow students and examiners as a fair and honest view on both programming languages. 

== Functional programming
[quote, Eric Elliot]
____
Functional programming (often abbreviated FP) is the process of building software by composing pure functions, avoiding shared state, mutable data, and side-effects. Functional programming is declarative rather than imperative, and application state flows through pure functions. Contrast with object oriented programming, where application state is usually shared and colocated with methods in objects. paragraph.footnote:[https://medium.com/javascript-scene/master-the-javascript-interview-what-is-functional-programming-7f218c68b3a0]
____

=== Basics of functional programming

Functional programming heavily differs from object orientation in Java or C#. As it is summarized in above statement, functional programming trades shared state in instantiated objects for the composition of pure functions. With functional programming the developer describes a set of functions that can be invoked when supplying certain input. The design of those is similiar to the concept of mathematical functions, which use conditionals and recursion to perform computation. Functional programming code tends to be more readable, easier to test and has a higher predicatbility than OO or procedural developed code. In compination with the missing shared state, it also tends to be less buggy, because without state there can't be sideffects from an inconsisten state. Newcomers originating from OO or procedural programming languages often struggle to get started with FP because of the mindset and common patterns associated with it which differ vastly from those in OOP for example.

FP languages can be divided into two segments:

* Pure Functional languages, which only support the functional paradgims (i.e. no state).
* Impure Functional languages, which grant the possibility to use other OO or procedural related concepts.

=== Functional languages ruleset

As with any programming paradigm, branding a certain ruleset on it is rather difficult. Over time some rules arose that FP languages and programmers __should__ follow to stick as close as possible to the paradigms paragraph.footnote:[https://thecodeboss.dev/2016/12/core-functional-programming-concepts/]

. Functions are pure, meaning that everytime the function gets called, with identical input, it produces the same output and does not inflict side effects (i.e. altering/creating state).
. Functions are first class and higher order. First class roughly means that a variable can be assigned a function. This in combination with 'higher order' imposes that functions can be arguments/input parameters to other functions.
. Variables should be immutable. Once a variable gets created and assigned, its value should never change again. Operations altering variable state should result in an assignment to a __new__ variable.
. Any function should be __referential transparent__. This means that any occurance of a call to a function __method(5)__ can be replaced with the returned value of said method without changing the programs behaviour and state. 

== GO programming language
=== General
[quote, Wikipedia]
____
Go is a statically typed, compiled programming language designed at Google by Robert Griesemer, Rob Pike, and Ken Thompson. Go is syntactically similar to C, but with memory safety, garbage collection, structural typing, and CSP-style concurrency.
____
The Go programming language first got presented by Rob Pike at Google around 2009, with it's first stable release following three years later in 2012. It got created as a response to Javas or C++ inadequacies and suitability for scaling cloudcomputing services.

Heavily influenced by the programming language _C_, Go delivers procedural programming features, object orientation and functional programming.  
On the following pages this article will be focusing on the functional programming aspects. 

=== Functional Programming in GO
Since functional programming in __Go__ is neither the only nor the main aspect, it belongs to the **Impure Functional languages**. Further, it wasn't designed to be a functional programming language. This is easily spotted by the absence of builtin functions like 'Map', 'Filter' and 'Reduce'. To be fair, they can be easily implemented using Gos functional aspects but aren't part of the main framework. Being an impure functional language also means that it doesn't enforce the rules stated in <<Functional languages ruleset>>. For example it is perfectly fine in go to write following code:
[source, go]
----
name_string := "Daniel"
name_string := name_string + "Piotrowski"
----
For this to be more in line with the functional paradigms it should be rewritten in:
[source, go]
----
first_name := "Daniel"
last_name := "Piotrowski"
full_name := first_name + " " + last_name
----
In the first example the state of the __name_string__ variable changes multiple times where as in the second every variable is treated as immutable and therefor adherent to the FP paradigms.

==== First-class and higher-order
In Go every function can be stored into a variable and passed to a function as input. For example this can be used to create filter method for an array of integers.
[source, go]
----
func filter(input []int, filterFunction func(int) bool)(ret []int){
	for _, i := range input{
		if filterFunction(i){
			ret = append(ret, i)
		}
	}
	return
}
----
This function takes an array of integers and a function as input. Next it applies the input function on every index of the input array, if the condition returns true, it appends to the return array. With this we can create filter methods for even and odd numbers.
[source, go]
----
odd_func := func(i int) bool {return i%2 == 1}
even_func := func(i int) bool {return i%2 == 0}
----
With these two we can now filter an array in integers.
[source, go]
----
package main

import "fmt"

func main() {
	input := []int{1,2,3,4,5,6,7}
	odd_func := func(i int) bool {return i%2 == 1}
	even_func := func(i int) bool {return i%2 == 0}

	fmt.Println(filter(input, odd_func)) // returns [1 3 5 7]
	fmt.Println(filter(input, even_func)) // returns [2 4 6]
}

func filter(input []int, filterFunction func(int) bool)(ret []int){
	for _, i := range input{
		if filterFunction(i){
			ret = append(ret, i)
		}
	}
	return
}
----
As a side-note the __filter__ function is pure, as it does not depend on external/global state, references, etc. It only takes the inputs and creates something new (a new array) with them and returns it.

==== Recursion
Typically a pure FP language, like Haskell, favors recursion over looping. As Golang is an impure FP language, one can do an iterative or a recursive approach to solve loop-scenarios.
[source, go]
----
func fib_it(n int) int{
	a := 0
	b := 1
	for i := 0; i < n; i++ {
		temp := a
        a = b
        b = temp + a
	}
	return a
}
----
In this code example we have calculated the n'th fibonacci number using a loop-iterative approach. For recursion, this can written down into:
[source, go]
----
func fib_rec(n int) int{ // note: do not run for higher than 40. It *will* take ages...
	if n == 0 || n == 1{
		return n
	} else{
		return fib_rec(n-1) + fib_rec(n-2)
	} 
}
----

==== Currying, Composition and Closure

A closure is a function (called parent-function) that takes input parameters and returns another function (called child-function). During the execution of the parent-function local state of variables can be bound into returned child-function. These bounded variables can be accessed through the closures copies or references to the value. Golang supports the use of Closures:
[source, go]
----
func counter_closure(n int) func() int {
	counter:= 0
	return func() int{
		counter += n
		return counter
	}
}

counterIncrease3 := counter_closure(3) // counter is 0
counterIncrease3() // counter is 3
counterIncrease3() // counter is 6
----

Here the enclosing function and the anonymous return function share the local state of the variable __counter__, hence the __counterIncrease3__ method can be created to increase __counter__ by 3 every time it is called.

The technique of Currying is splitting a single function that takes a number of arguments into multiple functions that take a single argument, but are called in sequence for computation. In Go it can be achieved simply by expanding the Closure return function to accept an additional parameter.
[source, go]
----
func add(n, i int) int {
    return n + i
}
func curried_add(n int) func(int) int {
	return func(i int) int{
		 return n + i
	}
}
add(5,3) // returns 8
curried_add(5)(3) // returns 8
----

Composition is the act of composing multiple functions into a single function with a single return value. With Closures and Currying this can be easily achieved.
[source, go]
----
func mult(a int) func(int) int{
	return func(i int) int{
		return a * i
	}
}
pow := func(i int) int {return mult(i)(i)} 
pow(3) // returns 9
----


== F# programming language

[quote, F#.org]
____
F# is a strongly-typed, functional-first programming language for writing simple code to solve complex problems. From the business perspective, the primary role of F# is to reduce the time-to-deployment for robust software in the modern enterprise and web applications. paragraph.footnote:[https://fsharp.org/about/]
____

F# ([ɛfː ʃɑrp]) is a "functional-first" Functional Programming language designed, developed and maintained by Microsoft. It first released in 2002 and has since been part of Microsofts .NET Framework which F# gets developed alongside with. Currently (31.12.2020) it shares the same major version as the new .NET Framework (5). 

=== General
Being heavily influenced by Objective CAML, C# and Haskell, the F# language is not a pure functional language, but in comparison to Golang it __was__ designed to be a functional language on top of the .NET Framework. Additional to the functional aspects, F# also allows for object oriented and imperative programming (i.e. type-classes, for/while-loops). This allows for a full interoperability with Microsofts allaround object oriented C# programming language which preceeds F# by one year.

=== Functional programming in F#

One can easily get started with Functional programming in F# by downloading the .NET Framework from official Microsoft pages and creating a new console application with Microsofts Visual Studio IDE or with the __dotnet-cli__. Taking a lot from OCAML, F# syntax introduces recursive functions by using the keyword __rec__ infront of the functions name. Another example of syntax familarities is __match ... with ...__ which allows for implementing switch-case scenarios.

[source, f#]
----
let rec test n =
    match n with
    | 0 -> 1
    | x -> n + test (n-1)
----

F# is more in line with the <<Functional languages ruleset>> as it introduces scope based variable imutability. On a module level (F# organises function-sets into modules, just like go), a __let__ declaritive must be unique, in a function scope multiple let assignments of the same variable name are allowed, however omitting the __let__-keyword produces a compiler error since by default, all variables in F# are immutable.
[source, f#]
----
// ex1:
let test1 = 5
let test1 = 7 // produces a compilation error 
//-----------\\
// ex2:
let test1 = 5
let f x = 
	let test1 = 2 // in function scope -> okay
	test1 = 7 // error, variable is immutable
	let test1 = 8 // technically okay, inside a function, doesn't make sense
	test1 * x // 8 * x
----

While applying __ex2__ the declaration of the last let assignment of__test1__ inside the __f-function__ hides the value of all previous (same-level and outer scope) of the __test1__ variable, hence using the same variablename with a let-declaritive is not reasonable. Since F# provides OO features, imutability becomes unhandy when dealing with objects. F# offers the keyword __mutable__. Using this allows the programmer to change the value of a already defined variable. So rewriting the the ex2 of the previous code snippet results in:
[source, f#]
----
let f x = 
	let mutable test1 = 2 
	test1 <- 7 // variable is mutable
	test1 * x // 7 * x
----

==== First-class
Being a "functional-first" language, F# functions are both first-class citizens and of higher order. This means functions are treated as values and can thus be given to other functions as arguments.
[source, f#] 
----
let f x = x + 2
let g f x = 2 * f (x)
----

==== Recursion 
Similiar to Go, F# offers the possibility to solve problems iterative and recursive. Thus implementing the calculation of fibonacci numbers can take 2 forms.
[source, f#]
----
// iterative
let fib_iter n = 
    let mutable a = 0
    let mutable b = 1
    for i in 0 .. n-1 do
        let temp = a
        a <- b
        b <- temp + a
    printfn "%i" a

// recursive, note again: this will take ages for higher indices...
let rec fib_rec n = // recursive functions need to be declared with the 'rec' keyword
    match n with
    | 0 | 1 -> n
    | x -> fib_rec (x-1) + fib_rec (x-2)
----

In conclusion, F# is a usefull, easy to get started with FP language, which provides everything necessary to do functional programming. Its interoperability with the .NET framework makes it possible to use almost the same, if not the same functionality scope as C#. As a result, writing entire http-webservers is possible using F#.

==== Closures, Composition and Currying
Close to what Go offers, F# can produce function Closures, Composition and Currying as well.
[source, f#]
----
// ----- Closure
let closure n =
    let mutable c = 0
    fun () -> (
        c <- c + n
        c
    )
let closure2 = closure (2)
printfn "%i" (closure2 ()) // prints 2
printfn "%i" (closure2 ()) // prints 4

// ----- Currying
let curried_add n = 
    fun c -> c + n 
printfn "%i" (curried (5) (4)) // prints 9

// ----- Composition
let pow n = n * n
let negate n = n * -1
let pn = pow >> negate
let np = negate >> pow
printfn "%i" (np 3) // prints 9
printfn "%i" (pn 3) // prints -9
----
== Comparison F# and Go
As the previous chapters show, functional programming idioms can be uphold to a certain degree with F# and Go. Nonetheless as stated by before, Go was not designed to be a functional language whereas F# was specifically created to give .NET developers a functional programming language. Compared to the ruleset provided in <<Functional languages ruleset>> F# is closer to being a **pure** functional language than Go is. This becomes more obvious by examining the given code examples. 

Although both languages share a lot of similiarities, writing functional code feels more 'natural' in F# than in Go. This is mainly due to the reason that in Go you __have to__ specify return types like `func add(a, b int) int {...}` or `func anonFunc (a int) func (int) int {...}`. In F# on the other side you __can__ specify input and output types. As a result the functional code written is much more readable.

As in terms of more simiarities the following table <<_table-comp,F# vs Go>>

.F# vs Go
[cols="^,^,^"]
|===
|Feature | F# | Go

|Garbage Collector| icon:check[] | icon:check[]
|Native executables| icon:check[] | icon:check[]
|Cross plattform| icon:check[] (given .NET Core only the runtime is needed on machine) | icon:check[] (needs to be target compiled)
|Module based| icon:check[]|icon:check[]
|Access control| functions top-level are public by default, can be marked `private, internal` | depends on capitalized letter `func Function` -> public `func function` -> private
| Typesystem | strong, nominal, with static typechecking | strong, structural, with static typechecking
|===

As a conclusion, both languages offer a similiar featureset, a rich base framework and a large community to support development. For functional programming F# takes the edge as its specific design to be a functional language makes it feel more suitable for purely functional scenarios.